国际化支持 nce you are satisfied with your changes, run
  git rebase --continue

  Administrator@DESKTOP-J80C12S MINGW64 /d/hello/work/WineYard/myapp
  (master|REBASE-i 1/3)
  $ git commit --amend --reset-author
  [detached HEAD 517ddbf] 项目结构搭建
   9 files changed, 19 insertions(+), 20 deletions(-)
    create mode 100644 src/store/actions.ts
     create mode 100644 src/store/getters.ts
      create mode 100644 src/store/mutations.ts
       create mode 100644 src/store/states.ts
        delete mode 100644 src/views/About.vue
	 rename src/views/{ => home}/Home.vue (72%)
	  rename src/views/{login.vue => login/Login.vue} (93%)

	  Administrator@DESKTOP-J80C12S MINGW64
	  /d/hello/work/WineYard/myapp (master|REBASE-i 1/3)
	  $ git rebase --continue
	  Stopped at 92f0136...  左侧导航搭建
	  You can amend the commit now, with

	    git commit --amend

	    Once you are satisfied with your changes, run

	      git rebase --continue

	      Administrator@DESKTOP-J80C12S MINGW64
	      /d/hello/work/WineYard/myapp (master|REBASE-i 2/3)
	      $ git commit --amend --reset-author
	      [detached HEAD d9a7784] 左侧导航搭建
	       3 files changed, 133 insertions(+), 24 deletions(-)
	        rewrite src/App.vue (67%)

		Administrator@DESKTOP-J80C12S MINGW64
		/d/hello/work/WineYard/myapp (master|REBASE-i 2/3)
		$ git rebase --continue
		Stopped at 933f6ba...  路由框架的搭建
		You can amend the commit now, with

		  git commit --amend

		  Once you are satisfied with your changes, run

		    git rebase --continue

		    Administrator@DESKTOP-J80C12S MINGW64
		    /d/hello/work/WineYard/myapp (master|REBASE-i 3/3)
		    $ git rebase --continue
		    Successfully rebased and updated refs/heads/master.

		    Administrator@DESKTOP-J80C12S MINGW64
		    /d/hello/work/WineYard/myapp (master)
		    $ git push
		    http://xieyunzhou@192.168.1.158/sms/sms-web.git
		    master
		    warning: redirecting to
		    http://192.168.1.158/sms/sms-web.git/
		    To http://192.168.1.158/sms/sms-web.git
		     ! [rejected]        master -> master
		     (non-fast-forward)
		     error: failed to push some refs to
		     'http://xieyunzhou@192.168.1.158/sms/sms-web.git'
		     hint: Updates were rejected because the tip of your
		     current branch is behind
		     hint: its remote counterpart. Integrate the remote
		     changes (e.g.
		     hint: 'git pull ...') before pushing again.
		     hint: See the 'Note about fast-forwards' in 'git
		     push --help' for details.

		     Administrator@DESKTOP-J80C12S MINGW64
		     /d/hello/work/WineYard/myapp (master)
		     $ git pull
		     http://xieyunzhou@192.168.1.158/sms/sms-web.git
		     master
		     warning: redirecting to
		     http://192.168.1.158/sms/sms-web.git/
		     From http://192.168.1.158/sms/sms-web
		      * branch            master     -> FETCH_HEAD
		      Auto-merging src/views/login/Login.vue
		      Merge made by the 'recursive' strategy.

		      Administrator@DESKTOP-J80C12S MINGW64
		      /d/hello/work/WineYard/myapp (master)
		      $ git push
		      http://xieyunzhou@192.168.1.158/sms/sms-web.git
		      master
		      warning: redirecting to
		      http://192.168.1.158/sms/sms-web.git/
		      Enumerating objects: 33, done.
		      Counting objects: 100% (33/33), done.
		      Delta compression using up to 8 threads
		      Compressing objects: 100% (14/14), done.
		      Writing objects: 100% (17/17), 1.89 KiB | 644.00
		      KiB/s, done.
		      Total 17 (delta 9), reused 0 (delta 0)
		      To http://192.168.1.158/sms/sms-web.git
		         933f6ba..0d35003  master -> master

			 Administrator@DESKTOP-J80C12S MINGW64
			 /d/hello/work/WineYard/myapp (master)
			 $ git checkout -b xieyunzhou
			 Switched to a new branch 'xieyunzhou'
			 M       src/App.vue
			 M       src/views/querySystem/LeadingIn.vue
			 M       src/views/querySystem/SendQuery.vue

			 Administrator@DESKTOP-J80C12S MINGW64
			 /d/hello/work/WineYard/myapp (xieyunzhou)
			 $ git add .

			 Administrator@DESKTOP-J80C12S MINGW64
			 /d/hello/work/WineYard/myapp (xieyunzhou)
			 $ git commit -m '国际化支持' .
			 [xieyunzhou 089ec10] 国际化支持
			  3 files changed, 152 insertions(+), 169
			  deletions(-)
			   rewrite src/App.vue (93%)
			    copy src/{App.vue => components/Menu.vue}
			    (90%)

			    Administrator@DESKTOP-J80C12S MINGW64
			    /d/hello/work/WineYard/myapp (xieyunzhou)
			    $ git remote add origin